In [1]:
import pandas as pd

In [3]:
path =r'C:\Users\M.Brooks\Desktop\PythonFiles\Untitled Folder\dublinbikes_20190401_20190701.csv'
testDF = pd.read_csv(path)

In [5]:
testDF.head(5)

,STATION ID,TIME,LAST UPDATED,NAME,BIKE STANDS,AVAILABLE BIKE STANDS,AVAILABLE BIKES,STATUS,ADDRESS,LATITUDE,LONGITUDE
0,2,2019-04-01 00:00:06,2019-03-31 23:52:05,BLESSINGTON STREET,20,14,6,Open,Blessington Street,53.35677,-6.26814
1,2,2019-04-01 00:05:04,2019-04-01 00:02:13,BLESSINGTON STREET,20,14,6,Open,Blessington Street,53.35677,-6.26814
2,2,2019-04-01 00:10:04,2019-04-01 00:02:13,BLESSINGTON STREET,20,14,6,Open,Blessington Street,53.35677,-6.26814
3,2,2019-04-01 00:15:03,2019-04-01 00:12:21,BLESSINGTON STREET,20,14,6,Open,Blessington Street,53.35677,-6.26814
4,2,2019-04-01 00:20:03,2019-04-01 00:12:21,BLESSINGTON STREET,20,14,6,Open,Blessington Street,53.35677,-6.26814

In [11]:
stationDF = testDF.groupby('NAME').mean()
print(stationDF.head(5))
print()
print(len(stationDF))

                    STATION ID  BIKE STANDS  AVAILABLE BIKE STANDS  \
NAME
AVONDALE ROAD            108.0         40.0              31.201699
BARROW STREET             70.0         28.0              16.616186
BENSON STREET             90.0         40.0              28.726540
BLACKHALL PLACE           88.0         30.0              15.609418
BLESSINGTON STREET         2.0         20.0              14.785533

                    AVAILABLE BIKES   LATITUDE  LONGITUDE
NAME
AVONDALE ROAD              8.786301  53.359406  -6.276142
BARROW STREET             13.619018  53.341656  -6.236198
BENSON STREET             11.186003  53.344154  -6.233451
BLACKHALL PLACE           14.389766  53.348801  -6.281637
BLESSINGTON STREET         5.193299  53.356770  -6.268140

113

In [10]:
stationDF.sort_values('AVAILABLE BIKES', ascending=False, inplace=True)
stationDF.head(10)

,STATION ID,BIKE STANDS,AVAILABLE BIKE STANDS,AVAILABLE BIKES,LATITUDE,LONGITUDE
NAME,,,,,,
HEUSTON STATION (CENTRAL),93.0,40.0,14.538857,25.458551,53.346603,-6.296924
HEUSTON STATION (CAR PARK),94.0,40.0,16.207843,23.783229,53.346985,-6.297804
HEUSTON BRIDGE (NORTH),92.0,40.0,16.726300,23.268708,53.347801,-6.292432
TALBOT STREET,38.0,40.0,20.228436,19.682379,53.350975,-6.252940
PARKGATE STREET,86.0,38.0,18.824365,19.162771,53.347973,-6.291804
GEORGES LANE,50.0,40.0,21.679163,18.315797,53.350231,-6.279696
SMITHFIELD NORTH,42.0,30.0,11.661163,18.292133,53.349564,-6.278198
KILLARNEY STREET,115.0,30.0,12.589017,17.351846,53.354843,-6.247579
EMMET ROAD,83.0,40.0,22.924831,17.064657,53.340714,-6.308191
SANDWITH STREET,64.0,40.0,23.240052,16.692075,53.345203,-6.247163

In [15]:
AvondaleDF = testDF[testDF['NAME']=='AVONDALE ROAD']
print(AvondaleDF.head(5))
print()
print(len(AvondaleDF))

       STATION ID                 TIME         LAST UPDATED           NAME  \
30135         108  2019-04-01 00:00:06  2019-03-31 23:53:03  AVONDALE ROAD
30136         108  2019-04-01 00:05:04  2019-04-01 00:03:11  AVONDALE ROAD
30137         108  2019-04-01 00:10:04  2019-04-01 00:03:11  AVONDALE ROAD
30138         108  2019-04-01 00:15:03  2019-04-01 00:13:20  AVONDALE ROAD
30139         108  2019-04-01 00:20:03  2019-04-01 00:13:20  AVONDALE ROAD

       BIKE STANDS  AVAILABLE BIKE STANDS  AVAILABLE BIKES STATUS  \
30135           40                     32                8   Open
30136           40                     32                8   Open
30137           40                     32                8   Open
30138           40                     32                8   Open
30139           40                     32                8   Open

             ADDRESS   LATITUDE  LONGITUDE
30135  Avondale Road  53.359406  -6.276142
30136  Avondale Road  53.359406  -6.276142
30137  Avondale Road  53.359406  -6.276142
30138  Avondale Road  53.359406  -6.276142
30139  Avondale Road  53.359406  -6.276142

20833